name: order_food
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.0
  geolocator: ^6.1.14
  http: ^0.12.2
  carousel_slider: ^3.0.0
  firebase_auth: ^0.20.1
  cloud_firestore: ^0.16.0+1
  shared_preferences: ^0.5.12+4
  firebase_core: ^0.7.0
  provider: ^4.3.2+1
dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true

  assets:
    - asset/images/
  
  fonts:
    - family: mont
      fonts:
        - asset: asset/Montserrat-Medium.ttf
         
 
